# Generated by Django 2.2 on 2019-06-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contect',
            new_name='Contact',
        ),
    ]
