# Generated by Django 2.2 on 2019-06-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_pages', '0002_auto_20190608_0307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
