# Generated by Django 2.2 on 2019-06-14 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursesdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='image')),
                ('time', models.CharField(max_length=250)),
                ('fee', models.CharField(max_length=250)),
                ('read_more', models.CharField(max_length=500)),
                ('add_date', models.DateField(auto_now=True, null=True)),
                ('overview_titles', models.CharField(max_length=250)),
                ('overview', models.TextField()),
                ('syllabus_title', models.CharField(max_length=250)),
                ('syllabus', models.TextField()),
                ('training_methodology_title', models.CharField(max_length=250)),
                ('training_methodology', models.TextField()),
                ('upcoming_batches_title', models.CharField(max_length=250)),
                ('upcoming_batches', models.TextField(blank=True)),
                ('additional_title1', models.CharField(max_length=250)),
                ('additional_topic1', models.TextField(blank=True)),
                ('additional_title2', models.CharField(max_length=250)),
                ('additional_topic2', models.TextField(blank=True)),
                ('additional_title3', models.CharField(max_length=250)),
                ('additional_topic3', models.TextField(blank=True)),
                ('course_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='Detail_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('courseimg', models.FileField(upload_to='')),
                ('syllabus', models.TextField(max_length=10000)),
                ('batch', models.TextField(max_length=400)),
                ('traning', models.TextField(max_length=1000)),
                ('traning_fee', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('quary_more', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Full_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_topic', models.CharField(max_length=200)),
                ('about', models.TextField(max_length=20000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Coursesdata')),
            ],
        ),
    ]
