# Generated by Django 2.2 on 2019-06-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesdata',
            name='additional_title1',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
