# Generated by Django 2.2 on 2019-06-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190614_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Full_course',
        ),
    ]
